[package]
name = "ld51"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
koi3 = {path = "../koi3"}
klog = {path = "../koi2/crates/klog"}
rapier2d = "0.14.0"